### PR TITLE
Remote connection enabled

### PR DESCRIPTION
**Pull request by b1gb1t**
Remote connection to frida-server listener

### CODE REVIEW

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t many thanks for your pull request.

I tested the new remote connection feature with my Amazon Fire TV but unfortunately without success.

That's what I did:

```
adb connect my_ip
./frida-server &
adb disconnect
```

Remote Connection: my_ip:5555 
RMS is not able to spawn the app.

**Am I missing something?**

I usually use the "adb connect my_ip" command to manage the device as if it is connected via USB. 
I'm afraid that if you not use "adb connect", you always have to insert the IP address in the device page of RMS and, considering that RMS is currently stateless (it is not able to remember device parameters), this will be a pain.

What you think about? What's your use case?
Thanks

**Comment by b1gb1t** [comment]
Hey!

The PR allows remote connections using the listener of frida-server. I mean, you have to run frida-server with the following command:
`frida-server -l 0.0.0.0:1337 -D`

Then, frida-server will allow for remote connections. If you use frida-cli you can connect running the following command:
`frida -H <ip_device>:<port> .........`

**Comment by realgam3** [comment]
> ws remote connections using the listener of frida-server. I mean, you have to run frida-server with the following command:

This feature now exist as a configuration parameter :)

**Comment by b1gb1t** [comment]
Nice!! I saw the PR. 
But IMHO, I prefer to set up the IP and PORT outside the config file. For example, I usually work with diferents devices and if I have to modify a config file whenever I change the device the process becomes more "complex".

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t yes sorry but I prefer to keep remote connection config inside the "config.json" file. In this way you don't have to manually insert the IP again if you need to restart the session. If you want to support the project you can work to make the config file editable directly via the web interface. It will be much appreciated.

@realgam3 PR has been merged yesterday.
Thanks for your understanding

**Comment by b1gb1t** [comment]
Perfect! I will work to make the config file editable.
Thanks for your development

**Pull request closed without merging**
