### PR TITLE
Config TAB

### PR DESCRIPTION
**Pull request by b1gb1t**
Added new TAB to modify the config file. Also I added a try/except in device_management() to avoid Internal Error if the device is not connected. 
Maybe the connection to the device should be established after submit the main form on "/".  What do you think?

### CODE REVIEW

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t may thanks for you new PR.
I just tested your work and I have some comments :)

1. You have inserted the option to manage Local, Remote and USB devices but the ID option is missing. Can you add it?
2. When you write the config inside the JSON file, spaces must be trimmed (especially for the system_package field)
3. I would like to show the management option inside the Device tab (e.g. USB/Remote etc...). Just below the non editable label containing the persistence process hooked by RMS.
4. Can you kindly edit the statement "Edit this setting directly in the configuration file (config.json)" in Device Tab in something like "You can Edit this setting directly in the Config tab"
5. I would like to show the ability to add device args only if "host" or "id" are selected. I also would like to keep fixed the label of the field (e.g. host) and leave the user the ability to only add the value (e.g. IP:PORT please add a placeholder)

I know that task n°5 requires some effort. So please let me know if you have time to work on this. If not, I'll merge your PR as soon as I have time to complete all the tasks.

Regarding your question, if the connection is established after the submit, the new package auto-complete feature added by @realgam3 will not work. Any suggestion to improve the user-experience?

Best
Paolo

**Comment by m0bilesecurity** [comment]
That's amazing! Many thanks for the time spent on the project.

I think that the connect button is the only option we have but probably I prefer to have the auto connection ON instead of a  connect button. 

Please open a different pull request if you want to work on that point so we can evaluate case by case 😉

**Comment by b1gb1t** [comment]
Frida connection errors due to the new code are fixed in last commit 5966e43.

Some details about the new commit 879affb:

- Option to dynamically add arguments has been removed. Now the web application shows the correct argument related to device connection (Remote and ID).
- Device tab shows device connection (type and arguments).
- config.json always have all possible arguments to improve user-experience (imho). In this way, the the user can reuse the information.

**Comment by b1gb1t** [comment]
Regardin the package auto-complete feature and UX, If the connection is not established with the device you can redirect the user to config tab. This way, the user will not see an internal error and could modify the connection settings to try again.

I tried the solution locally but I need the config tab, so when PR is merged and if you like the solution I will create a new PR.

**Comment by m0bilesecurity** [comment]
Ciao @b1gb1t I performed a quick test and it seems **amazing**. Many thanks for your work.

I agree with you that instead of a connect button, a good solution is to automatically redirect the user to the config page (we have it now 👍 ) if RMS is not able to find a device.

So if you already have the work done, you can commit here without opening a different PR. 

Let me know
Paolo

**Comment by m0bilesecurity** [comment]
Great @b1gb1t, I'll review the new config tab later this afternoon ;)
I just had a quick look at the code. Is **flash** from Flask really needed?

Thanks

**Comment by b1gb1t** [comment]
True! I added flash but finally I didn't use it because I needed a session.
Fixes in 732a4e4

**Comment by m0bilesecurity** [comment]
Ciao @b1gb1t,
config tab looks great now!
Just a small bug: If the device is not connected I now receive the warning (great!). But if I connect the device and reload the Device page, RMS is not able to recognize the device. In order to get the device detected, I'm forced to reload the python app.

**Comment by b1gb1t** [comment]
True... I've tested remote connection and works fine, but USB doesn't. 
I don't know why. I need to research more.

**Comment by b1gb1t** [comment]
Hey @m0bilesecurity 
I think it will be better to set the PR on commit 5966e43 while I research the solution. When I have it I'll open a new PR.

**Pull request merged**
