### PR TITLE
Update Requirements.txt

### PR DESCRIPTION
**Pull request by pollonegro**
WebSocket transport not available. Install gevent-websocket for improved performance.

### CODE REVIEW

**Comment by m0bilesecurity** [comment]
Hey @pollonegro, many thanks for the PR. Can you kindly add more details?
gevent and gevent-websocket have been added to the Requirements.txt file but they have never been used.

Many thanks

**Comment by m0bilesecurity** [comment]
Hey @pollonegro I followed your suggestion and I can confirm that
using `gevent/gevent-websocket` the UI does not freeze anymore. Unfortunately the output loading inside the web console is super slow! 

**Any idea how to tweak it?**
Thanks

**Comment by pollonegro** [comment]
Sorry @m0bilesecurity for not answering before, I've been very busy.
As you say, the output load within the web console is very slow, although in my case it goes very well.
I take this opportunity to thank you for this great tool and everything that can help, count on me!
a greeting @m0bilesecurity

**Comment by m0bilesecurity** [comment]
Hey @pollonegro, many thanks for you precious support. 

By simply adding gevent and gevent-websocket the UI does not freeze anymore during socketIO but, at least on my mac, all the socket.emit calls have a delay of about 10 seconds.

I need more time to investigate. 
Best

**Comment by pollonegro** [comment]
Thanks for the advice, ur awesome. 😉

**Pull request closed without merging**
