### PR TITLE
Fix hook template where classname has '.' in it.

### PR DESCRIPTION
**Pull request by wabzqem**
For example, if the classname is `Slack.FeatureFlagManager`, the iOS hook template currently fails. Using the [ ] notation fixes this.

### CODE REVIEW

**Comment by m0bilesecurity** [comment]
Hey @wabzqem many thanks for the PR.
The same fix should also work for the **template_massive_hook_iOS** var, can you kindly check?
That template is used by the "Hook all methods" button in Dump page.

Many thanks

**Comment by wabzqem** [comment]
Thanks, updated and checked this worked too.

**Comment by m0bilesecurity** [comment]
I also checked your commit this morning.
Awesome PR 🎉
Many many thanks!

**Comment by m0bilesecurity** [comment]
New package 1.5.3 is up on **npmjs** 🎉

[NPM](https://npmjs.org/package/rms-runtime-mobile-security)

**Pull request merged**
