### PR TITLE
Remote connection fix

### PR DESCRIPTION
**Pull request by b1gb1t**
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/issues/47#issue-758398201

### CODE REVIEW

**Comment by m0bilesecurity** [comment]
Many thanks for this PR 🙏🏻
I've just uploaded the new npm package containing your fix 😉

[NPM](https://npmjs.org/package/rms-runtime-mobile-security)

**Comment by b1gb1t** [comment]
nice @m0bilesecurity !

But I am working on new PR. The addRemoteDevice() function  is called incorrectly in the following line.
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/7090a9152870a3f365c96e1fdc4f7432c59f9623/app.js#L489

Also I have other kind of errors, for example:

> Exception: ReferenceError: device is not defined
> com.android.systemui is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
> Excpetion: TypeError: device.spawn is not a function

So I try to PR asap when I fix it. If you wish, you can update line 489.

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t thanks! 🎉
Let me know once done 🙏

**Comment by m0bilesecurity** [comment]
> Also I have other kind of errors, for example:
> 
> > Exception: ReferenceError: device is not defined
> > com.android.systemui is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
> > Excpetion: TypeError: device.spawn is not a function

Are they happening when a remote device is connected or also with USB device?

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t 
I fixed the call at line 489 (commit 1e86a1c)
If there are other issues with remote device please let me know.
When everything is OK I'll create another npm package ;)
Thanks

**Comment by b1gb1t** [comment]
> > Also I have other kind of errors, for example:
> > > Exception: ReferenceError: device is not defined
> > > com.android.systemui is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
> > > Excpetion: TypeError: device.spawn is not a function
> 
> Are they happening when a remote device is connected or also with USB device?

Only with remote devices. USB connection seems to be working fine!

**Pull request merged**
